---
- hosts: control
  remote_user: root
  vars:
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_201"
    java_archive: "{{download_folder}}/jdk-8u201-linux-x64.tar.gz"


  tasks:
    - name: Download Java
      synchronize:
        src: /root/jdk-8u201-linux-x64.tar.gz
        dest: /opt/ creates={{java_archive}}
      delegate_to: 192.168.177.162

    - name: Unpack archive
      command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

    - name: Fix ownership
      file: state=directory path={{java_name}} owner=root group=root recurse=yes

    - name: Make Java available for system
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

    - name: Clean up
      file: state=absent path={{java_archive}}


